import type { AppProps } from 'next/app';
import Head from 'next/head';
import '../app/globals.css'; // Adjust the path to your globals.css file


export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* Ensure to add the Google Fonts link here if necessary */}
        
      </Head>
      <Component {...pageProps} />
    </>
  );
}
